version: '3.8'
services:
  app:
    container_name: library_management_app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Passw0rd!
      DB_NAME: librarydb
      JWT_SECRET: super-ultimate-secret
      ADMIN_EMAIL: admin@example.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      NODE_ENV: development
  db:
    container_name: library_management_db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd!
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
